"""Init models

Revision ID: 315d54e59430
Revises: 
Create Date: 2026-07-01 00:04:29.996554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '315d54e59430'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('venue_name', sa.String(), nullable=False),
    sa.Column('venue_city', sa.String(), nullable=True),
    sa.Column('team1_id', sa.Integer(), nullable=False),
    sa.Column('team2_id', sa.Integer(), nullable=False),
    sa.Column('toss_winner_id', sa.Integer(), nullable=False),
    sa.Column('toss_decision', sa.String(), nullable=False),
    sa.Column('outcome_winner_id', sa.Integer(), nullable=True),
    sa.Column('outcome_by_runs', sa.Integer(), nullable=True),
    sa.Column('outcome_by_wickets', sa.Integer(), nullable=True),
    sa.Column('outcome_result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['outcome_winner_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team1_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team2_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['toss_winner_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_season'), 'matches', ['season'], unique=False)
    op.create_table('innings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('innings_number', sa.Integer(), nullable=False),
    sa.Column('batting_team_id', sa.Integer(), nullable=False),
    sa.Column('bowling_team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batting_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['bowling_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('innings_id', sa.Integer(), nullable=False),
    sa.Column('over_number', sa.Integer(), nullable=False),
    sa.Column('delivery_number', sa.Integer(), nullable=False),
    sa.Column('ball', sa.String(), nullable=False),
    sa.Column('batter_id', sa.String(), nullable=False),
    sa.Column('bowler_id', sa.String(), nullable=False),
    sa.Column('non_striker_id', sa.String(), nullable=False),
    sa.Column('batter_runs', sa.Integer(), nullable=False),
    sa.Column('extras', sa.Integer(), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('is_wicket', sa.Boolean(), nullable=False),
    sa.Column('player_out_id', sa.String(), nullable=True),
    sa.Column('wicket_kind', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['batter_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['bowler_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['innings_id'], ['innings.id'], ),
    sa.ForeignKeyConstraint(['non_striker_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_out_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deliveries')
    op.drop_table('innings')
    op.drop_index(op.f('ix_matches_season'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
